version: '3.11'
services:
  ####################
  backend:
    build: .
    command: "uvicorn app/main:app --reload"
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - database
  ####################
  database:
    image: latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop_fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - app_network
    ports:
      - "5432:5432"
  ###################
volumes:
  postgres_data:
networks:
  app_network: