version: '3.10.10'
services:
  ####################
  web:
    build: .
    volumes:
      - ./:/app
    command: /bin/sh -c 'alembic upgrade head && python -m app'
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - database
  ####################
  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop_fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - app_network
    ports:
      - "5432:5432"
  ###################
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    container_name: rabbitmq_broker
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app_network
    ports:
      - "5672:5672"
      - "15672:15672"
  ###################
  celery:
    build: .
    working_dir: /app
    restart: always

    container_name: celery_worker
    volumes:
      - ./:/app
    command: celery -A app.tasks.worker worker -l info
    networks:
      - app_network
    depends_on:
      - rabbitmq
    ##################
  celery-beat:
    build: .
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    command: celery -A app.tasks.worker beat -l info
    networks:
      - app_network
    depends_on:
      - rabbitmq
      - celery
  ######################
  flower:
    build: .
    restart: always
    container_name: flower
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "celery -A app.tasks.worker flower  --address=0.0.0.0 --port=5566 && 
      celery -A app.tasks.worker flower --broker=amqp://rabbitmq:5672"
    networks:
      - app_network
    ports:
      - '5566:5566'
    depends_on:
      - celery
      - celery-beat
      - rabbitmq
  ######################
volumes:
  postgres_data:
networks:
  app_network: