version: '3.10.10'
services:
  ####################
  web:
    build: .
    volumes:
      - ./:/app
    command: /bin/sh -c 'alembic upgrade head && python -m app'
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - database
  ####################
  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop_fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - app_network
    ports:
      - "5432:5432"
  ###################
volumes:
  postgres_data:
networks:
  app_network: