"""second

Revision ID: 17a4ca6cce31
Revises: 0e8b69d423b8
Create Date: 2023-02-27 18:58:01.619194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a4ca6cce31'
down_revision = '0e8b69d423b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
