"""Removed all lazy relationships in models

Revision ID: 49c111761c1a
Revises: 8618f9e15fcf
Create Date: 2023-04-02 22:58:01.693394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c111761c1a'
down_revision = '8618f9e15fcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
