"""Second

Revision ID: 8618f9e15fcf
Revises: b893538f0ebe
Create Date: 2023-03-29 16:36:11.268992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8618f9e15fcf'
down_revision = 'b893538f0ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
